name: Sicily Photos Georgios
favicon: null
layout_spectrum: 0.09182
typography_spectrum: 0.4929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21864221477881074
  lightness: 0.04023905796930194
  saturation: 0.5409641712903976
  rhythmicContrast: 0.42233265563845634
purpose: []
